### ISSUE TITLE
Question about Ingest data `is_deceased` and `lost_followup_after_clinical_event_identifier`

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/candigv2-ingest#115]
Hi CanDIG team folks:

I am trying to ingest the clinical data into CanDIG by:

`python katsu_ingest.py --input my_redcap_data`

And got the error like this about donor PR-CY-FAKE-0004:
<img width="949" alt="image" src="https://github.com/user-attachments/assets/94ced80b-008b-479f-a435-a39674ae034f">

But the donor's data is: 

<img width="829" alt="Screenshot 2024-09-20 at 2 26 52 PM" src="https://github.com/user-attachments/assets/7bfb8860-cbbb-4079-9450-3031b6f6fc39">

his `is_deceased=No`, not dead. What could be the reason for this error?

When I used CSVConvert to generate this json data file, I don't get warning or error message. 
<img width="348" alt="image" src="https://github.com/user-attachments/assets/ee8815a7-98db-4abe-bbd8-2bcf2b36950b">

I took out this info and set `is_deceased` to `Yes` and delete the 2 following 2 lines about `lost_followup_`. It looks data is ingested (since there already existing data in the server, I could not tell). The results is:

<img width="449" alt="image" src="https://github.com/user-attachments/assets/83819f1d-6a7e-47e3-ad11-5fc92b1c7abf">

Can you tell from the results if any data is ingested?

I appreciate it if you can shed me some light. 

Best,
Ray

**Comment by mshadbolt** [comment]
Hi Ray

Apologies for the delayed response, I am working on an update to the latest model which I think should fix this issue, stay tuned!

**Comment by mshadbolt** [comment]
I think version 3.1.0 of clinical_etl should fix this issue, please try updating ingest so that it uses this version and let me know if you are still getting this error.

**Comment by rjiang9** [comment]
This issue has been fixed as @mshadbolt said above. Ticket is closed.
