### ISSUE TITLE
Register program

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/candigv2-ingest#130]
Hi Marion, 

Sorry to bug you gain:

I have the Candig working fine (The office wired network contributed a lot to my previous test-integration failures) and the data portal works well.

But when I tried to get to the data  ingesting, I ran into an problem:
1) I got Bearer token OK
2) When I tried the clinical ingest program registration code:

```
curl -s --request POST \
  --url $CANDIG_URL'/ingest/program' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer '$TOKEN \
  -d '{"program_id": "PR-CY-FAKE", "program_curators": [ "user1@test.ca"], "team_members": ["user2@test.ca"]}'
```

I got 
```
{
    "error": "Key not authorised"
}%                             
```

Here is the screenshot:
<img width="791" alt="image" src="https://github.com/user-attachments/assets/a28c3ae7-71e6-43f5-8085-1f359c7498f6">

Do you happened to know where to look into? I appreciate it for any light you shed. @mshadbolt 

Best,
Ray

**Comment by mshadbolt** [comment]
Hi Ray, great to hear your stack is up and running. We get this kind of error usually if there is something wrong with the token, like it didn't get copied properly or perhaps truncated or expired.

You can try printing out the token to double check it is saved properly in TOKEN, I would probably also double check your candig url just to make sure

```
echo $CANDIG_URL
echo $TOKEN
```

You can also check the validity of the token it prints out by copying and pasting it to  [jwt.io](https://jwt.io/)  - you can hover over the "exp" field to see if it has expired. Hope this helps!

**Comment by rjiang9** [comment]
Hi Marion, 
Thank you for getting back to me so quickly. I followed your suggestions and both $CANDIG_URL and $TOKEN look fine. 

So I did a CanDig rebuild and program registration went well:

<img width="1091" alt="image" src="https://github.com/user-attachments/assets/ec2d12fd-ff5a-4e45-a4d7-acfdfdfd104e">

Thank you again,
Ray

**Comment by rjiang9** [comment]
That was caused by the bad token.  Thanks @mshadbolt . 

I am closing this ticket.
