### ISSUE TITLE
test data issue

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/candigv2-ingest#89]
Hi @mshadbolt and the develop team, 

I continue to try out the CanDIGv2 and still got some issues after the upgrade to 4.0.0.

1) `requires.txt`
```
PyYAML==6.0.1
requests==2.31.0
requests-mock>=1.11.0
urllib3==1.26.18
minio==7.1.7
jsoncomparison~=1.1.0
candigv2-authx@git+https://github.com/CanDIG/candigv2-authx.git@v2.2.2
awscli==1.29.5
python-dotenv==0.14.0
dateparser~=1.2.0
pandas~=2.1.4
numpy>=1.22.2 # not directly required, pinned by Snyk to avoid a vulnerability
clinical_etl@git+https://github.com/CanDIG/clinical_ETL_code.git@v2.2.0
```
2.
`git submodule status`
<img width="660" alt="image" src="https://github.com/CanDIG/candigv2-ingest/assets/7293118/f0f96ad4-8b10-437c-829c-5438df3aa7ba">

3. `make test-integration`
make-test-integration.txt
[make-test-integration.txt](https://github.com/CanDIG/candigv2-ingest/files/15001226/make-test-integration.txt)

5. Issues:
`python katsu_ingest.py --input tests/clinical_ingest.json`
<img width="717" alt="image" src="https://github.com/CanDIG/candigv2-ingest/assets/7293118/60e7ed7c-71c9-4749-8fd4-9f3c2c6f93c1">

There are still a lot fails in the `make test-integration`, please suggest what we did wrong with the setup and for the dates in the ingest test clinical data(see the above screen), how we can get rid of date-related errors. 

Thanks a lot,
Ray

**Comment by mshadbolt** [comment]
Hi Ray, 
Are you able to confirm the steps you took to upgrade to v4.0.0? And also what kind of system you are deploying this on?

In case you have missed any steps, I have summarized below what I do when I want to change versions, all commands assume you are in the `CanDIGv2` repo:

You would need to first clean out the existing containers and images, (this deletes everything including databases and volumes so anything you want to keep should be backed up) 
```
make clean-all
```
Then you can checkout the stable release commit of the repo like this:
```
git checkout stable
```
Make sure you update all submodules by running
```
git submodule update --init --recursive
```
Copy over the version of `.env` and update with any edited values. I usually save the older version and copy things across
```
mv .env .env-bak
cp etc/env/example.env .env
```
Things you may have changed could be the architecture and IP address depending on how you are deploying.

Once these steps have completed you are ready to build the images with the updated submodules. this can be done with 
```
make install-all
```
It is possible this might not work on some mac architectures, in that case try:
```
rm -r bin # this is where miniconda installs
make bin-conda
make init-conda
make build-all
```

As each image builds and composes, it should give feedback on whether it is successful and you should see the services coming up in docker. At the end it will report on whether all the services are up. After that you can run the integration tests and see whether things are running as expected. Let me know how you go.

**Comment by rjiang9** [comment]
Thank you so much for the detailed info on how to upgrade the CanDIG. I will be forwarding the info to our system admin. I know our deployment is on a Rocky Linux 9.3 on a Cloudstack. 

Ray

**Comment by rjiang9** [comment]
Thanks again for your solution, @mshadbolt. This works great. I am closing the ticket now.
