### ISSUE TITLE
Question about the post-install test data and schema

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/candigv2-ingest#90]
Hi @mshadbolt and all dev folks,

I got a question for the [post installation test data ](https://raw.githubusercontent.com/CanDIG/candigv2-ingest/f7eed947dc45cc9002fe89b331d5c3819ea77c0e/tests/clinical_ingest.json)and the [schema](https://raw.githubusercontent.com/CanDIG/katsu/develop/chord_metadata_service/mohpackets/docs/schema.yml). @mshadbolt mentioned last time that the `date formats` is an object in `dateInterval` format now instead of a string. The object has 'number of days and months since first diagnosis': 

<img width="500" alt="image" src="https://github.com/CanDIG/candigv2-ingest/assets/7293118/502ce60e-95ed-47a6-8f4f-7c404c38c5e1">

The 'date_of_diagnosis' object is supposed to be {days: 0, months: 0} as in most places in the json data file, but on line 200-205, the days and monts are not 0, see:
<img width="716" alt="image" src="https://github.com/CanDIG/candigv2-ingest/assets/7293118/09be8f9a-5621-4d02-8bf1-e4446864a0dc">

Why is the date_of_diagnosis object data not 0? what is the logic? I appreciate it if you can give me a hint. 

Thanks,
Ray

**Comment by mshadbolt** [comment]
Hi Ray, thanks for the question! 

In our understanding of the MoH model, it is possible for a Donor to have multiple linked Primary Diagnoses. We assume that the earliest diagnosis is the index date that we use to calculate all the other dates related to a Donor, this earliest diagnosis would have 
```
'date_of_diagnosis': {
    'day_interval': 0, 
    'month_interval':0
}
```
In the example you have shared from our test data in ingest, you will see that there is a second Primary Diagnosis linked to `DONOR_2`, `PD_2_1` that does have the date of diagnosis as described above. Whereas the diagnosis with id `PD_2` happened 21 months after that initial diagnosis. I know it is a bit counterintuitive to have multiple 'primary' diagnoses.

Let me know if you have any other questions or anything doesn't make sense!

**Comment by rjiang9** [comment]
Got it. Thank you so much for making it clear to me, Marion. I appreciate it.

**Comment by mshadbolt** [comment]
You're welcome! Feel free to reach out if you have any other questions!
