### ISSUE TITLE
how do I get the authorized bearer token for API ingest?

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/candigv2-ingest#96]
Hi dev team folks, 

I am testing the ingest function and ran into a question. In the README.md file, regarding using API method to ingest in `How to use candigv2-ingest` section,  how do I get the authorized bearer token? This may be a basic question but it's out of my knowledge. I tried `curl -k -c cookie -d username=user2 -d password=user2Password http://docker-container:8080/` but got nothing. 

Any instruction is appreciate it. 

Thanks a lot,
Ray

<img width="866" alt="image" src="https://github.com/CanDIG/candigv2-ingest/assets/7293118/9f049133-816f-4bc3-b23b-f15cbb473332">

**Comment by mshadbolt** [comment]
Hi Ray!

If you are logged into the VM where candig is deployed, and inside the CanDIGv2 repo, you can try the following:

Load the env variables into the terminal session
```
source env.sh
```
Do a curl to get the site admin tokens
```
CURL_OUTPUT=$(curl -s --request POST \
  --url $KEYCLOAK_PUBLIC_URL'/auth/realms/candig/protocol/openid-connect/token' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data grant_type=password \
  --data client_id=$CANDIG_CLIENT_ID \
  --data client_secret=$CANDIG_CLIENT_SECRET \
  --data username=$CANDIG_SITE_ADMIN_USER \
  --data password=$CANDIG_SITE_ADMIN_PASSWORD \
  --data scope=openid)
```
store the token in the variable `$TOKEN`
```
export TOKEN=$(echo $CURL_OUTPUT | grep -Eo 'access_token":"[a-zA-Z0-9._\-]+' | cut -d '"' -f3)
```
double check the token was stored:
```
echo $TOKEN
```
should be a long character string jwt

**Comment by rjiang9** [comment]
Hi Marion, 

Thank you so much for your quick and detailed response. You code snippet works like a charm. I appreciate it.
Have a great weekend. @mshadbolt 

Ray

**Comment by rjiang9** [comment]
HI Marion, 

I reopen this ticket since I am thinking that it may be related to the original question of mine (Data ingest):

1. On the `develop` branch, I noticed the `command line ingest for clinical data` has been removed from the README.md. My question is: Can I still use the cmd tool to ingest? The clinical ingest on my server still have not working well yet, I just wonder about it. 
2. I installed Katsu on my local computer, what's the way to ingested my redcap data (json format from ETL_code)? From the 
the web interface, I don't see the place to let you upload and import the whole data file. What is the best way to do it including get the authorized bearer token?

Thanks a lot and have a nice weekend,
Ray 

<img width="654" alt="image" src="https://github.com/user-attachments/assets/9678008f-5710-4d45-b07f-ea92c38c6d9a">

<img width="474" alt="image" src="https://github.com/user-attachments/assets/681f1b99-9632-4c33-8fd2-07717cccab41">

**Comment by mshadbolt** [comment]
Hi Ray, we are in the process of refining the workflow for ingest so we should have some updates for you soon.

We are focusing on ingest via API for now, we don't currently have a UI based solution for this.

**Comment by mshadbolt** [comment]
Hi Ray, thanks for your patience. We have incorporated a lot of changes into develop and are currently preparing for a stable release. If you would like to be some what of a beta tester you could checkout the latest develop branch and try installing it locally on your laptop. I think this would be easier that trying to install katsu and ingest separately. 

You can try following the instructions here to install the candig stack (I recently updated them so hopefully they are easy to follow but lets us know if you run into any issues: 
https://github.com/CanDIG/CanDIGv2/blob/develop/docs/install-candig.md

Once you have the stack up and running, you can try running through the instructions in the candig-ingest readme to ingest data into the stack. We have incorporated a way for users to get a token from the data portal once it is running which should be easier. 

Let us know how you go!

**Comment by rjiang9** [comment]
Thanks Marion for the updates. I will test it out on my local by your suggestions.

**Comment by rjiang9** [comment]
Hi Marion,

I have been trying to install candig stack (develop branch) by the installation guide on my Macbook pro. Everything looks good until I got to `make build-all`:
5) Build and test:
        make test-integration

<img width="1151" alt="image" src="https://github.com/user-attachments/assets/d14ff05e-b2cd-4b0b-8e9d-fc1067094d82">

<img width="942" alt="image" src="https://github.com/user-attachments/assets/3ea13892-05fb-46bd-8a7e-5fa1ece0d154">


Here is the tmp/error.txt:
[error.txt](https://github.com/user-attachments/files/17403390/error.txt)


[progress.txt](https://github.com/user-attachments/files/17403391/progress.txt)


[containers.txt](https://github.com/user-attachments/files/17403393/containers.txt)

It'll be great if you can give me some idea about what. I missed. 

Thanks,
Ray

**Comment by mshadbolt** [comment]
Hi Ray, 

Good job on getting the stack going! It looks like all the containers built and started okay but something is going wrong when we are trying to ingest. Not sure how quickly you ran the tests but sometimes waiting a little while after the build manages to clear things up. Can you try running the same integration tests again with `make test-integration`

After that, if the first ingest test is still failing, can you try adding a line to 
`etc/tests/test_integration.py` at line 459, to print out the response you are getting, for some reason it seems like you aren't getting a queue_id in the response, so want to check what the response looks like.

So the current file would look like:
https://github.com/CanDIG/CanDIGv2/blob/e13ffeecc0734c81c9c921a1f1fb2910def6d7a9/etc/tests/test_integration.py#L457C4-L459C9
```
# When program authorization is added, ingest should be allowed
    response = requests.post(f"{ENV['CANDIG_URL']}/ingest/clinical", headers=headers, json=test_data)
    try:
```
and we want to update it to:
```
# When program authorization is added, ingest should be allowed
    response = requests.post(f"{ENV['CANDIG_URL']}/ingest/clinical", headers=headers, json=test_data) 
    print(response.json())
    try:
```

Then try running
```
make test-integration-test_ingest_not_admin_katsu
```
which should print out the information we are interested in

If you could also share the central log which is found in `/tmp/logs/` the file will probably start with `buffer.` then a long string, then end in `.log`

**Comment by mshadbolt** [comment]
Hi Again! Can you also please try to pull the latest version of katsu, and regenerate the test data as we made a patch to the schema yesterday

From the candigv2 repo:
```
git pull
git submodule update
make recompose-katsu
python lib/candig-ingest/candigv2-ingest/generate_test_data.py --tmp tmp/data/synthdata
```

**Comment by rjiang9** [comment]
Hi Marion, 

Sorry for the late reply. I did check out the patch code but not run through. Since I am not in office, it looks the candig docker does not running well (was it because the Local_IP change?). I will try it out including your solution above tomorrow and report back here. 

My apologies. 

Best,
Ray 

> ```
> git pull
> git submodule update
> make recompose-katsu
> python lib/candig-ingest/candigv2-ingest/generate_test_data.py --tmp tmp/data/synthdata
> ```

**Comment by rjiang9** [comment]
Hi Marion, 

I have done another test by checkout new code. the `make test-integration` just got one failed on `test_federation_call`:

<img width="1317" alt="image" src="https://github.com/user-attachments/assets/22442c21-6cb5-4631-8a22-f40952c1e1e6">
<img width="752" alt="image" src="https://github.com/user-attachments/assets/2c9b1b99-e2ec-41f2-a32d-24244a34a8ea">

Have a great weekend,
Ray

**Comment by rjiang9** [comment]
> Hi Again! Can you also please try to pull the latest version of katsu, and regenerate the test data as we made a patch to the schema yesterday
> 
> From the candigv2 repo:
> 
> ```
> git pull
> git submodule update
> make recompose-katsu
> python lib/candig-ingest/candigv2-ingest/generate_test_data.py --tmp tmp/data/synthdata
> ```

Hi Marion, 

This works and synthetic data is generated and copied to the `tests/` folder in `CanDIGv2/lib/candig-ingest/candigv2-ingest` but when I tried to run: 

` python katsu_ingest.py --input tests/SYNTH_01.json`


I got errors of 400 and here is the running output:

```
 **** status_code : 400
 **** json_data: {'errors': {'SYNTH_01': [{'not found': 'No program authorization exists'}]}}
 **** schemas: ['errors']
```

There are warnings in validation. Please refer to the full result output:
[errors.txt](https://github.com/user-attachments/files/17465097/errors.txt)

Please advice. 

Thanks,
Ray

**Comment by mshadbolt** [comment]
Hi Ray, the synthetic data in the ingest/tests folder should be ingested automatically when you run the integration tests, you just need to make sure that in your .env you have: `KEEP_TEST_DATA=true` , you should be able to view it in the portal after the tests have run.

If you do want to ingest it separately you would first need to register the program, which is explained in the README here: https://github.com/CanDIG/candigv2-ingest#1-program-registration

**Comment by rjiang9** [comment]
> response = requests.post(f"{ENV['CANDIG_URL']}/ingest/clinical", headers=headers, json=test_data) 
>     print(response.json())

Hi Marion, 
Here are the 2 files for the test that you suggested in this reply post:

[info-for_marion.txt](https://github.com/user-attachments/files/17465549/info-for_marion.txt)

`>> If you could also share the central log which is found in /tmp/logs/ the file will probably start with buffer. then a long string, then end in .log`

[buffer.b624f39218d99be26f3d137e457168470.log](https://github.com/user-attachments/files/17465565/buffer.b624f39218d99be26f3d137e457168470.log)

Please let me know if you need more info. 

Thanks for your help,
Ray

**Comment by mshadbolt** [comment]
Awesome, looks like the test is passing now, can you confirm that all your integration tests are now passing?

**Comment by rjiang9** [comment]
> Awesome, looks like the test is passing now, can you confirm that all your integration tests are now passing?

Hi Marion, 

the `make test-integration` still failed with 

`etc/tests/test_integration-0.py::test_federation_call FAILED                                                                [ 43%]`

screenshot as posted above. 

I noticed this solution, but it looks it does not work for me. 

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/77c7e336-2b75-4e8c-b701-9e6707c605a2">

`Federation` is in the CANDIG_MODULES list and `KEEP_TEST_DATA=true` in `.env`

1. I did

```
make clean-federation
make build-federation
make compose-federation
```

`make compose-federation` threw some errors:

<img width="583" alt="image" src="https://github.com/user-attachments/assets/578e7ec4-ee18-428d-a4da-256bc1a2a7a0">

2. re-run `make test-integration` and still got 2 'federation_call` failures. 

<img width="932" alt="image" src="https://github.com/user-attachments/assets/7e084d3a-4319-4d4f-a202-be8f11478f87">


3. Data portal login as site_admin@test.ca, and see NO data there. 
<img width="1464" alt="image" src="https://github.com/user-attachments/assets/47ebbcd3-b88d-40d5-b51c-70c3c1ced9fa">

I know this is tedious but still looking for its working on local. 

Thanks a lot,
Ray

**Comment by rjiang9** [comment]
I am working on apple 'M3' chip:
<img width="199" alt="image" src="https://github.com/user-attachments/assets/f38dc602-6ebb-4e5e-8704-522d43696d75">

And I followed the steps for Apple Silicon on CanDIGv2 docs:

<img width="549" alt="image" src="https://github.com/user-attachments/assets/71c388c9-6f4c-4bc2-9b14-eba03ab26678">

**Comment by mshadbolt** [comment]
Hi Ray, sorry this it is still not working for you and for all the back and forth

We have been recently changing some federation things so this might be why it isn't working, hopefully we are very close to solving it. 

Can you let me know what you get from
```
git submodule status
```

and share your .env?

**Comment by rjiang9** [comment]
Hi Marion, 

Here is what I got for `git submodule status`
```
(candig) ➜  CanDIGv2 git:(develop) ✗ git submodule status
+a0edc7f5b40e334c0de7bd796ad2842f094a22fc lib/candig-data-portal/candig-data-portal (v3.1.0-111-ga0edc7f)
 d36e1b47b2e310a04f64ec4897b423392d173aea lib/candig-ingest/candigv2-ingest (v4.1.0-97-gd36e1b4)
 11aabf1a339c9d1124cc459f3ced130ab03c46cc lib/federation/federation (v2.1.1-71-g11aabf1)
 a2290647d2cd66557302df62edfc36ec76264a26 lib/htsget/htsget_app (v4.1.0-98-ga229064)
 a7cec238304a245211d3ed80ef73fb3735840c81 lib/katsu/katsu_service (v5.0.0-8-ga7cec238)
 820a02f92d388ea385c0c21aeae396df7286108a lib/opa/opa (v3.0.0-56-g820a02f)
+8cd360765751d210a3df4fefaefebe23b69d6166 lib/query/query (v2.3.0-57-g8cd3607)
 b0ff5be051f2fd55352e00450b7848dcf8354a3b lib/toil/toil-docker (releases/5.5.0)
```
<img width="770" alt="image" src="https://github.com/user-attachments/assets/ccb55021-e5cf-4966-b559-295f17ebc295">

Here is my .env: 
[env.txt](https://github.com/user-attachments/files/17466792/env.txt)

Thanks, 
Ray

**Comment by mshadbolt** [comment]
Hi Ray,

Can you please try pulling latest changes from develop, update your submodules and recopy across the example env and edit it with the same changes, ie. update KEEP_TEST_DATA to true, input your local_ip address as before and update VENV_OS to arm64mac

```
git pull
git submodule update
cp etc/env/example.env .env # then update the new .env
make recompose-federation
make recompose-query
make recompose-candig-data-portal
make test-integration
```

**Comment by rjiang9** [comment]
Hi Marion,

1) when run `make recompose-federation`
<img width="602" alt="image" src="https://github.com/user-attachments/assets/e2e0328a-c9a4-48ca-8381-97ff801779bc">

2) when run `make recompose-query`

<img width="389" alt="image" src="https://github.com/user-attachments/assets/da0c5c14-0c47-4300-baf6-3292a87167ed">

3) run `make test-integration`

The first run:
<img width="995" alt="image" src="https://github.com/user-attachments/assets/8196dc7f-0279-4bfd-a3d9-5d2ee5d46c5b">
Then run:
<img width="1111" alt="image" src="https://github.com/user-attachments/assets/b7f34972-0997-4fd0-aadb-b9e0d8a3552a">
3rd run, all passed. 


4) Makefile - I use my existing `miniforge3` for the conda installation and get the error like this. I commented the line 
<img width="522" alt="image" src="https://github.com/user-attachments/assets/ea5fa830-add9-40de-83a3-7f1b4f30229c">

**Comment by daisieh** [comment]
That 400 error for "path is already in use" is normal: we always try to make the vault path during startup, even if it's already there; there's no harm in that.

**Comment by mshadbolt** [comment]
that federation test failure might be okay and not affect the actual stack running.

Are you able to access the data portal? http://candig.docker.internal:5080/

**Comment by rjiang9** [comment]
Hi Marion, 

I have just done a test from scratch and `make test-integration` passed without errors on my Macbook pro. 

The only thing might be Line 84 in `Makefile`. It failed on me because I have my own existing conda installed - `miniforge3`. I commented out and `bin-conda` passed.  

<img width="438" alt="image" src="https://github.com/user-attachments/assets/d88cebe6-55d9-4a37-81de-8fe0540fc524">


The front end http://candig.docker.internal:5080/ looks good too. 

<img width="1235" alt="image" src="https://github.com/user-attachments/assets/a51791da-6dcf-4348-9772-f7922d709424">

I am going to ingest some test data and see how it looks. 

Thank you and the team again for all your help. I look forward to the coming stable release. 

Sincerely,
Ray

**Comment by rjiang9** [comment]
I think this ticket can be closed (again). take care.

**Comment by mshadbolt** [comment]
Great to hear it is up and running, hope the ingest goes smoothly and it helps with your testing!

We will take a look into the conda failure, we might need to adjust the instructions for people with existing installations. Thanks for reporting the error.
