### ISSUE TITLE
How to wipe out test data

### ISSUE THREAD

**Issue by rjiang9** [CanDIG/candigv2-ingest#98]
Hi Marion @mshadbolt  and dev team folks:

One quick question about the Ingest: In the  CanDIG server`.env`, the `KEEP_TEST_DATA` was set to 'true' in order to see the post-install test results.

What would be the best way to clean up the test data?  

Thanks,
Ray

**Comment by mshadbolt** [comment]
Hi Ray, I think the easiest way would be to change the .env variable KEEP_TEST_DATA to false , then re run the integration tests.

**Comment by rjiang9** [comment]
Great, thanks a lot, Marion! @mshadbolt . I am going to try it out later today.
